name: flutter_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  get_it: ^5.0.1
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  dartz: ^0.9.2
  carousel_slider: ^2.3.1
  responsive_framework: ^0.0.14
  cached_network_image: ^2.3.3
  flutter_rating_bar: ^3.2.0+1
  material_floating_search_bar: ^0.2.3
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

